/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_s21_double_to_science.check" instead.
 */

#include <check.h>

#line 1 "tests/test_s21_double_to_science.check"
#include <stdio.h>
#include <stdlib.h>

#include "../s21_string.h"


#line 8
// #test s21_double_to_science_small_positive
// char s21_str[10];
// char str[10];
// long double number = 2.5;
// s21_double_to_science(s21_str, number, 3, FALSE);
// sprintf(str, "%.3Le", number);
// ck_assert_str_eq(str, s21_str);

START_TEST(s21_double_to_science_zero)
{
#line 17
char s21_str[10];
char str[10];
long double number = 0;
s21_double_to_science(s21_str, number, 3, FALSE);
sprintf(str, "%.3Le", number);
ck_assert_str_eq(str, s21_str);

// #test s21_double_to_science_max_double
// char s21_str[10];
// char str[10];
// long double number = 16383.1;
// s21_double_to_science(s21_str, number, 3, FALSE);
// sprintf(str, "%.3Le", number);
// ck_assert_str_eq(str, s21_str);

// #test s21_double_to_science_small_negative
// char s21_str_new[20];
// char str_new[20];
// long double number = -1.2;
// int size_s21 = s21_double_to_science(s21_str_new, number, 3, FALSE);
// int size = sprintf(str_new, "%.3Le", number);
// ck_assert_str_eq(str_new, s21_str_new);
// ck_assert_int_eq(size, size_s21);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("s21_double_to_science");
    TCase *tc1_1 = tcase_create("s21_double_to_science");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_double_to_science_zero);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
